# Players library.
cc_library(
    name="players_lib",
    srcs=glob([
        "**/*.cc",
        "**/*.inc",
    ]),
    hdrs=glob(["**/*.h"]),
    deps=[
        "//lib:arbitrium_lib",
    ],
    visibility=["//games:__subpackages__"],
)
