# Core algorithms library.
cc_library(
    name="arbitrium_lib",
    srcs=glob([
        "src/**/*.cc",
        "src/**/*.inc"
    ]),
    hdrs=glob(["include/**/*.h"]),
    visibility=[
        "//games:__subpackages__",
        "//players:__subpackages__"
    ],
)
